services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localdb

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d localdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  back:
    build:
      context: ./back
      dockerfile: Dockerfile

    container_name: spring-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/localdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      postgres:
        condition: service_healthy

  front:
    build:
      context: ./front
      dockerfile: Dockerfile

    container_name: angular-frontend
    restart: unless-stopped

    environment:
      PORT: 4200

    ports:
      - "4200:4200"

    depends_on:
      - back

volumes:
  postgres_data: